---
- name: Verify stacks directory exists (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  file:
    path: "/home/{{ansible_user}}/stacks"
    state: directory

- name: Generate admin password hash
  when: inventory_hostname == groups['swarm_managers'][0]
  shell: echo $(htpasswd -nb {{traefik_admin_user}} {{traefik_admin_password}}) | sed -e s/\\$/\\$\\$/g
  register: traefikpassword

- name: Create docker-compose stack file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  template:
    src: traefik-stack.j2
    dest: /home/{{ansible_user}}/stacks/traefik-stack.yml
    mode: 0775

- name: Install jsondiff Python library
  when: inventory_hostname == groups['swarm_managers'][0]
  become: true
  become_method: sudo
  pip:
    name: jsondiff

- name: Install pyyaml Python library
  when: inventory_hostname == groups['swarm_managers'][0]
  become: true
  become_method: sudo
  pip:
    name: pyyaml

- name: Deploy stack from a compose file (on first swarm node)
  when: inventory_hostname == groups['swarm_managers'][0]
  docker_stack:
    state: present
    name: traefik
    compose:
      - /home/{{ansible_user}}/stacks/traefik-stack.yml
