---
- name: Check if Gluster plugin has already been initialized
  shell: docker plugin inspect glusterfs
  register: gluster_plugin_status
  ignore_errors: true

- name: Disable Docker Gluster plugin
  shell: docker plugin disable -f glusterfs
  when: gluster_plugin_status.rc == 0

- name: Update Docker Gluster plugin
  shell: docker plugin upgrade --grant-all-permissions glusterfs trajano/glusterfs-volume-plugin
  when: gluster_plugin_status.rc == 0

- name: Renable Gluster plugin
  shell: docker plugin enable glusterfs
  when: gluster_plugin_status.rc == 0
  
