---
- hosts: all
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: host-defaults

- hosts: swarm_managers
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: docker
    - import_role:
        name: swarm-managers

- hosts: swarm_workers
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: docker
    - import_role:
        name: swarm-workers

- hosts: gluster_nodes
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: gluster

- hosts: swarm_managers
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: traefik
    - import_role:
        name: portainer

- hosts: haproxy
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: haproxy
