---
- hosts: swarm_managers
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: upgrade-docker

- hosts: swarm_workers
  tasks:
    - include_vars: "{{playbook_dir}}/config.yml"
    - import_role:
        name: upgrade-docker
